### ISSUE TITLE
Initializing test library 'ExcelRobot' with no arguments failed

### ISSUE THREAD

**Issue by LexiPham** [zero-88/robotframework-excel#1]
Hi,

I'm running into this issue:

Initializing test library 'ExcelRobot' with no arguments failed: TypeError: super() takes at least 1 argument (0 g
iven)
Traceback (most recent call last):
  File "c:\python27\lib\site-packages\ExcelRobot\__init__.py", line 54, in __init__
    super().__init__(DateFormat(date_format, time_format, datetime_format),NumberFormat(decimal_sep, thousand_sep, precision),BoolFormat(bool_format))
==============================================================================

Could you please help?

Regards,

**Comment by zero-88** [comment]
Thanks @LexiPham for try out this lib.
It is issue that not compatible with python 2. Currently, I have not yet tested with python 2, I will fix soon.
Could you try via python 3 in meantime?

**Comment by en237** [comment]
just hit with the same issue.

+1 for python 2 compatibility

**Comment by en237** [comment]
fixed my issue by modifying `__init___` function in `__init__.py` file in ExcelRobot root folder like this

```python
    def __init__(self,
                 date_format='yyyy-mm-dd', time_format='HH:MM:SS AM/PM', datetime_format='yyyy-mm-dd HH:MM',
                 decimal_sep='.', thousand_sep=',', precision='2', bool_format='Yes/No'):
        logging.basicConfig()
        logging.getLogger().setLevel(logging.INFO)
        logger = logging.getLogger(__name__)
        logger.info('ExcelRobot::Robotframework Excel Library')
        # super().__init__(date_format, time_format, datetime_format, decimal_sep, thousand_sep, precision)
        # super().__init__(
        #     DateFormat(date_format, time_format, datetime_format),
        #     NumberFormat(decimal_sep, thousand_sep, precision),
        #     BoolFormat(bool_format))
        ExcelLibrary.__init__(self,
            DateFormat(date_format, time_format, datetime_format),
            NumberFormat(decimal_sep, thousand_sep, precision),
            BoolFormat(bool_format))
```

but that's specific for my python2.7 not sure if that's still works for python 3

**Comment by LexiPham** [comment]
Thanks for quick response, I'm able to use it now.

**Comment by zero-88** [comment]
Fixed.
Use command to install
`pip install https://github.com/zero-88/robotframework-excel/archive/master.zip`
Will be released on pypi soon
