### ISSUE TITLE
Write To Cell throws AttributeError 'NoneType'

### ISSUE THREAD

**Issue by edsonharantes** [zero-88/robotframework-excel#10]
**Describe the bug**
Keyword Write To Cell doesn't work, throws an error "AttributeError: 'NoneType' object has no attribute 'write_to_cell'"

**Environment**
- Library Version - 1.0.0b4
- Python Version - 3.7.1
- OS - windows 10

**To Reproduce**
Using the code:

    Open Excel   |   ${excel_file}
    Write To Cell |  ${excel_1}    | 0  | 8  | value

**Exception Log**
AttributeError: 'NoneType' object has no attribute 'write_to_cell'

**Comment by FrenchhMan** [comment]
Hi @edsonharantes 
did you find a solution for this bug? I have the same problem

**Comment by edsonharantes** [comment]
Hi @FrenchhMan, I end up creating my own excel library with this specify function only, although I'm still using this library to do other excel stuff.

I can put the function here so you can create your own file, or I can make a Pull Request to fix it (this is probably a bug in this library, I didn't have the time to investigate this issue further).

**Comment by FrenchhMan** [comment]
Hello @edsonharantes 
If you can give me your function, i will realy appreciate your help.

Thank's

**Comment by zero-88** [comment]
Hi @edsonharantes  @FrenchhMan 
Thanks for your report. Could you please let me know you are using excel `xls` or `xlsx`?
Currently, I'm busy with some stuffs, not yet have a look. 
I really appreciate and welcome if you can open PR to fix this

**Comment by FrenchhMan** [comment]
@zero-88 
xlsx for me.

**Comment by edsonharantes** [comment]
@zero-88  with ```xls``` files if I not mistaken, it works fine, I'm using the lasted version of excel, the files are saved as ```xlsx```


```python
from openpyxl import load_workbook

class excel(object):

    def __init__(self):
        print("hello world")

    def write_value_to_cell(self, workbook, sheet, cell, value):
        wb = load_workbook(filename = workbook)
        sheet_ranges = wb[sheet]
        sheet_ranges[cell] = value
        wb.save(workbook)
```

Write Value To Cell  |   excel file path   |    sheet    |     A11    |      I'm a value in A11

**Comment by FrenchhMan** [comment]
@edsonharantes your keyword works fine!!!
thank you so much.

**Comment by zero-88** [comment]
you can use https://zero-88.github.io/robotframework-excel/docs/ExcelRobot.html#Write%20To%20Cell%20By%20Name

Actually, it has a bug related to https://zero-88.github.io/robotframework-excel/docs/ExcelRobot.html#Write%20To%20Cell in my side but I cannot reproduce your case `"AttributeError: 'NoneType' object has no attribute 'write_to_cell'"`.

**Comment by zero-88** [comment]
if you don't mind, could you please help me try to test again with this artifact
`pip install https://github.com/zero-88/robotframework-excel/archive/bugfix/writer-error-due-to-robot-argument-is-string.zip`

Sample tests:
https://github.com/zero-88/robotframework-excel/blob/8c4a59b0f84c1812613b0f0ea50754dad897dfc1/tests/acceptance/ExcelRobotTest.robot#L77-L85

or do your own to see if this issue doesn't happen
Thank @FrenchhMan @edsonharantes

**Comment by zero-88** [comment]
Furthermore, `Open Excel` just for `reader`, `Open Excel To Write` for `writer`

**Comment by apuchkov** [comment]
Switching from `Open Excel` to `Open Excel To Write` fixed this issue for me. 

Seems like documentation here https://zero-88.github.io/robotframework-excel/docs/ExcelRobot.html needs to be updated as examples for `Write To Cell` and `Write To Cell By Name` mention `Open Excel` method instead of `Open Excel To Write`

Maybe also renaming `Open Excel` to `Open Excel To Read` will make it more clear that there's also `Open Excel To Write` keyword. Or alternatively, the exception could mention that the file was open for reading not for writing.
