### ISSUE TITLE
Start row and column numbers by 1

### ISSUE THREAD

**Issue by lucietriskova** [zero-88/robotframework-excel#12]
I would appreciate if the row and column numbers could start by 1, not by 0.
The reason is that robot framework in general is designed for people with limited or zero programming experience and therefore it's more natural to use the numbering starting by number 1.

**Example:**
right now, to get data of the A1 cell, I need to write:
`read cell data       Sheet1       0        0`

but it would be much more understandable if it was:
`read cell data       Sheet1       1        1`
- from this, even a junior test engineer or business analyst reviewing my scenarios can understand that I am reading the 1st cell of the 1st column

**Comment by zero-88** [comment]
You can use [Read Cell Data By Name](https://zero-88.github.io/robotframework-excel/docs/ExcelRobot.html#Read%20Cell%20Data%20By%20Name) and [Write To Cell By Name](https://zero-88.github.io/robotframework-excel/docs/ExcelRobot.html#Write%20To%20Cell%20By%20Name) by using `Excel convention name`, such as `A1`, `B2`, etc.

**Comment by lucietriskova** [comment]
cool, thanks! Actually by looking at the keyword "read cell data by name" I thought it means that it will select the cell by the named range... 
So all good, let's close this ticket then :D
