### ISSUE TITLE
[ ERROR ] Parsing 'ExcelRobotTest.xls' failed: Unsupported file format 'xls'.

### ISSUE THREAD

**Issue by vnvbsudhakar** [zero-88/robotframework-excel#5]
Unable to run ExcelRobotTest.robot because of this error.
[ ERROR ] Parsing 'ExcelRobotTest.xls' failed: Unsupported file format 'xls'

**Comment by vnvbsudhakar** [comment]
Thanks for the mail.
That issue was my bad. There was a mistake I made while I execute command to run your excel tests. 
I didn't find any option to delete this issue, so I closed it. I am going to use your library in my mobile test automation framework in robotframework. 
Thanks for doing this library.

**Comment by zero-88** [comment]
You're welcome.
If any issue when using this lib, let me know.
btw, install lib directly, instead of pypi:
```
pip install https://github.com/zero-88/robotframework-excel/archive/master.zip
```
