### ISSUE TITLE
Write to cell and write to cell name are not working with any combinations.

### ISSUE THREAD

**Issue by vnvbsudhakar** [zero-88/robotframework-excel#8]
Always I get below error when I use Write to cell and write to cell name.
AttributeError: 'ExcelWriter' object has no attribute 'number_format'

**Comment by zero-88** [comment]
@vnvbsudhakar Pls follow [Bug template](https://github.com/zero-88/robotframework-excel/blob/master/.github/ISSUE_TEMPLATE/bug_report.md)
Thanks
